### ISSUE TITLE
[BUG]DDBOT提示账号已冻结，但用其他方式是可以正常登陆的，希望作者可以考虑一下

### ISSUE THREAD

**Issue by FadeJay** [Sora233/DDBOT#100]
可参考python代码https://github.com/FadeJay/DecryptLogin/blob/master/bilibili.py
![QQ图片20211122093303](https://user-images.githubusercontent.com/15902208/142789166-a1f1708c-99d8-406d-af6c-5a189d61ca11.png)
操作系统版本：
BOT版本：
1.0.0

**Comment by Sora233** [comment]
暂未收到 https://bili.dev:2233/captcha 的授权

**Comment by FadeJay** [comment]
> 暂未收到 https://bili.dev:2233/captcha 的授权

我测试的时候并不会触发验证码，用不着https://bili.dev:2233/captcha
