### ISSUE TITLE
[FEATURE]您好 请问这个怎么和Steam_watcher结合使用呢

### ISSUE THREAD

**Issue by syxxjgh** [Sora233/DDBOT#101]
https://github.com/SonodaHanami/Steam_watcher
目前已经部署了一个基于yobot和go-cqhttp的steam_watcher的bot了

这个DDBOT也部署成功了 请问能对接yobot的推送么 不然需要2个qq号比较麻烦

**Comment by Sora233** [comment]
有两种办法：
- go-cq和ddbot使用相同的device.json
- go-cq和ddbot使用不同的device.json，同时使用不同的登录协议

**Comment by syxxjgh** [comment]
感谢 用了不同协议可以了
