### ISSUE TITLE
[BUG]Linux 下，在 application.yaml 输入 bilibili 账号密码后启动 DDBOT 后显示 bilibili 账号未配置

### ISSUE THREAD

**Issue by ldcivan** [Sora233/DDBOT#115]
**详细描述**
Linux 下，在 application.yaml 输入 bilibili 账号密码后启动 DDBOT 后显示 bilibili 账号未配置
**如果是私有部署**
操作系统版本：CentOS 7.4.1708 (AltArch) aarch64(Py3.7.8)
BOT版本：DDBOT-v1.0.2-linux-arm.tar.gz

麻烦烦您了

**Comment by Sora233** [comment]
尝试使用cookie配置
