### ISSUE TITLE
[FEATURE]readme.md和爱发电找不到赞助的渠道

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [Sora233/DDBOT#118]
**描述一下您的想法**
在readme.md和爱发电找不到赞助渠道，希望在readme.md中标注

**Comment by Sora233** [comment]
是故意的
在github页面右边Sponsor this project可以找到爱发电链接

**Comment by Waldo-Schaeffer** [comment]
> 是故意的 在github页面右边Sponsor this project可以找到爱发电链接

谢谢，感谢你的开源项目，对我和很多我喜欢的小可爱帮助很大[给心心]

**Comment by Sora233** [comment]
感谢你对开源项目的支持
