### ISSUE TITLE
[BUG]登录显示"packet timed out"

### ISSUE THREAD

**Issue by heartalborada-del** [Sora233/DDBOT#120]
**详细描述**
在删除device.json后登录显示:packet timed out
这里是log：[https://pastebin.ubuntu.com/p/StJMKZbQJ5/](https://pastebin.ubuntu.com/p/StJMKZbQJ5/)

**正常情况应该是怎样的**
应该是正常登录吧

**如果是私有部署**
操作系统版本：Windows server 2012R2
BOT版本：V1.0.3

**Comment by Sora233** [comment]
是新版本miraigo的问题，下版本会降级miraigo到之前的版本，可以先下载使用开发版：
https://github.com/Sora233/DDBOT/actions/runs/1779623026

**Comment by Sora233** [comment]
尝试使用v1.0.4版本
