### ISSUE TITLE
希望增加个性化功能

### ISSUE THREAD

**Issue by usadapekora0112** [Sora233/DDBOT#121]
由于bot要用于各V群，希望能增加点个性化内容：
（1）查成分功能，输入“/查成分 %用户名或者%uid号”，返回该用户关注的V列表
（2）自定义签到名称，输入“/签到”后，返回“签到成功，获得1%自定义的签到名称，现在有X%自定义的签到名称”
（3）自定义随机V事迹介绍，输入“/%自定义关键字”，返回“随机一条自定义的当前V的介绍内容”
         例如，自定义关键字“/豹豹”、自定义介绍内容3条“白神王八”、“白神钢板”、“5835”
         在群内输入“/豹豹”后，随机返回一条介绍内容“5835”

**Comment by Sora233** [comment]
2 3在v1.0.5版本中以自定义模板的形式可以实现，1属于自定义命令没有足够的动机加入ddbot
