### ISSUE TITLE
[FEATURE]添加一个希望重新扫码授权登录以重置账号风控状态的命令

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [Sora233/DDBOT#123]
目前我都是通过修改application.yaml的形式，将登录的QQ修改为另一个QQ号来清除登录缓存，然后停止BOT，删除配置文件中的QQ号再使用扫码登陆。感觉这样很麻烦

**Comment by Waldo-Schaeffer** [comment]
实际上需要的是清空登录缓存的命令（功能）

**Comment by Sora233** [comment]
手动删除session.token文件就行
