### ISSUE TITLE
[FEATURE]希望添加一个配置参数可以控制“巨量推送时的限流”推送的QQ群的数量

### ISSUE THREAD

**Issue by Waldo-Schaeffer** [Sora233/DDBOT#124]
1.0.4版本中添加了一个“增加巨量推送时的限流，当一次性推送至50个群以上时，将增加推送延迟避免被封qq号”，我希望能在application.yaml中添加一个参数，能够设置“50”这个数量（否则我自己编译设置成了10，一旦版本更新会覆盖掉我的设置需要重新编译）

**Comment by Sora233** [comment]
v1.0.5已实现
