### ISSUE TITLE
[BUG]同时打开多个群的开播通知时只会通知一个群

### ISSUE THREAD

**Issue by Fbk-waifu** [Sora233/DDBOT#129]
**详细描述**
对一个youtube用户开启多个QQ群的开播提示，只会有一个群会提示（可能是最后添加开播提示的那个群），已排除风控

**正常情况应该是怎样的**
对添加开播提示的所有群发送提示

**如果是私有部署**
操作系统版本：ubuntu 20.04.3
BOT版本：1.0.4

**Comment by Sora233** [comment]
查看日志`notify`相关内容，会有GroupCode字段，确认是否只有一条，还是所有订阅的QQ群都有？

**Comment by Fbk-waifu** [comment]
只有一条
