### ISSUE TITLE
[FEATURE]  希望可以控制命令前是否增加/（斜杠）

### ISSUE THREAD

**Issue by smyhm** [Sora233/DDBOT#140]
**描述一下您的想法**
如题，能否设置在自定义命令前是否需要加“/”（斜杠）命令才生效的开关，有些简短的命令必须加“/”有点麻烦，bot自带命令可以维持“/”

**Comment by smyhm** [comment]
补充一下，可以吧命令分为管理命令和用户命令，用户命令可以不带/，管理命令可以开关普通用户使用权限，这样会方便一点

**Comment by Sora233** [comment]
see [v1.0.7](https://github.com/Sora233/DDBOT/releases/tag/v1.0.7)
