### ISSUE TITLE
DDBOT在根目录产生文件（拉屎）

### ISSUE THREAD

**Issue by Sakuranda** [Sora233/DDBOT#156]
【打开藏在两层文件夹内的DDBOT】
root@sakuranda:~# ~/DDBOT/ddbot/DDBOT

【然而会在根目录拉屎】
root@sakuranda:~# ls
 application.yaml   bilirecorder   ddrec         ffmpeg                               logs           qrcode.png
 autorun.sh         DDBOT          device.json  ''$'\001''@'$'\264''F@p'$'\002''@8'   miraigo-logs   snap
root@sakuranda:~# 

还有请问下【''$'\001''@'$'\264''F@p'$'\002''@8'】这一坨是个啥东西？
萌新刚玩linux 还请多指教qaq

**Comment by Sakuranda** [comment]
知道了 DDBOT运行的环境是当前目录
cd到ddbot文件夹内再运行DDBOT程序就好了x

**Comment by Sora233** [comment]
有空一起拉屎
