### ISSUE TITLE
[BUG]关闭BOT之后过一段时间再开启，会一次性发送关闭期间的推送信息

### ISSUE THREAD

**Issue by G-Cutemon** [Sora233/DDBOT#170]
**详细描述**
不知道这个算不算是bug，还是我什么地方操作有误。有时候因为各种原因将机器人关闭之后，过几天再打开，就会立即推送前几天的开播信息和动态内容到群里。

**正常情况应该是怎样的**
开播提醒和动态往往是非常有时效性的东西，如果错过了实时推送的时间点，之后就不应该再进行推送，那会让人感到困扰。

**如果是私有部署**
操作系统版本：win10
BOT版本：v1.0.8

**Comment by Dian-JIu** [comment]
在部署指南内的application.yaml完整配置内有相应配置 可自行添加修改

onlyOnlineNotify: false  # 是否不推送Bot离线期间的动态和直播，默认为false表示需要推送，设置为true表示不推送

**Comment by G-Cutemon** [comment]
> 

非常感谢！之前没注意到qwq
