### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YangSen16520** [Sora233/DDBOT#175]
**详细描述**
运行一段时间后提示非法访问

**截图**
![QQ图片20220930215110](https://user-images.githubusercontent.com/106819753/193285032-1b3ddc95-22ed-4a2e-b721-3812157cbd0c.png)

**如果是私有部署**
操作系统版本：windows sever 2012 datacenter
BOT版本：1.0.8

**Comment by Waldo-Schaeffer** [comment]
访问B站的速度过快导致的，修改application.yaml的配置文件中的SocksCap64
