### ISSUE TITLE
[BUG] Acfun直播状态获取大量失败

### ISSUE THREAD

**Issue by ns920** [Sora233/DDBOT#221]
**详细描述**
订阅acfun直播后，Acfun直播状态获取大量失败
目测是由于acfun接口更新，现在需要在cookie中传递_did参数

**如果是私有部署**
操作系统版本：Windows Server 2022
BOT版本：1.1.0

**Comment by Sora233** [comment]
无法复现，a站接口https://live.acfun.cn/api/channel/list?count=100&pcursor=可以直接访问
