### ISSUE TITLE
[BUG]1.01版本依然存在401错误

### ISSUE THREAD

**Issue by zwj2333** [Sora233/DDBOT#223]
**详细描述**
使用screen持久化运行后，当时测试是没有问题的。但是过了大概一两天，就开始出现推送推迟的问题，进入后台就发现401错误。非法访问。
设置情况：QQ账号已登录，没有配置B站账号，只订阅了两个直播间。

**正常情况应该是怎样的**
这边直播之后，QQ会很快发出直播通知。

**截图**
如果有截图
可以放一下，请注意保护个人隐私。

![Snipaste_2023-04-18_16-08-40](https://user-images.githubusercontent.com/45174459/232714088-6277f1cb-5fdb-4feb-8919-89ad935b9b46.png)

**如果是私有部署**
操作系统版本：CentOS 7.6 64bit
BOT版本：1.0.1

**Comment by zwj2333** [comment]
![Snipaste_2023-04-18_16-15-17](https://user-images.githubusercontent.com/45174459/232715500-45fbc9e9-5a94-466c-a0e2-7f73e20f6e9a.png)
重启后，依然存在401问题。

**Comment by Dian-JIu** [comment]
code:-401 请配置b站使用

**Comment by zwj2333** [comment]
已经解决
