### ISSUE TITLE
[BUG]qq账号不能登录

### ISSUE THREAD

**Issue by hzq19950316** [Sora233/DDBOT#227]
**详细描述**
qq账号无法登录
全部文件都是由程序新生成的，
就填写了qq账号与密码，
其他的全部为默认设置

**截图**
![image](https://user-images.githubusercontent.com/35598669/237012115-b0731cf1-bfa3-411e-9d17-ebbb751c7b91.png)

**如果是私有部署**
操作系统版本：windows 10 21h2
BOT版本：v1.1.0

**Comment by NayuuHikari** [comment]
想问一下这个有解决吗，因为我的云服务器到期了，换了一个环境，重新登陆的时候也是这样，手机也没弹出验证，不填账号密码又说当前协议不支持二维码登陆
我是最新版本v1.1.1的
WARNING[2023-06-02T11:06:14+08:00] 登录失败: 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。 Code: 45  bot=internal
WARNING[2023-06-02T11:06:14+08:00] 你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证        bot=internal

**Comment by hzq19950316** [comment]
报登录失败建议更新版本Code: 45的处理办法
- 去device.json文件找到 "protocol":6 （默认是6）
- 将后面的数字改成3或者5 （3.Mac协议 5.iPad协议）
- 删除versions_6.json重启DDBOT等待协议更新（慢点正常 没报错就让他慢慢更新）
- 如果3 5都失效 那就用协议2（watch协议）注意要去application.yaml里面把账密删掉 不然会变成账密登录（watch协议只支持扫码登录）
- 注意：如果使用协议2的话需要在同一局域网内扫描登录，登录成功后再整个文件夹拷贝到服务器上使用。
