### ISSUE TITLE
[BUG] 你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。 Code: 45  bot=internal

### ISSUE THREAD

**Issue by itgoyo** [Sora233/DDBOT#238]
**详细描述**
DDBOT突然停止

**正常情况应该是怎样的**

12点钟之前还是好好的，下午就看到没有通知上去看，就报这个错了，不知道是不是QQ的原因

**截图**

<img width="1055" alt="image" src="https://github.com/Sora233/DDBOT/assets/23348551/8ffd06ff-6eaa-4c9a-a072-3c2881f6afed">

**如果是私有部署**
操作系统版本：ubuntu
BOT版本：v.1.1.1

**Comment by TeemoKill** [comment]
同样报错来蹲一下

操作系统版本：debian 11
BOT版本：v.1.1.1

**Comment by Sora233** [comment]
需要使用v1.2.2的signServer
