### ISSUE TITLE
请问可否增加扫码登录功能？

### ISSUE THREAD

**Issue by wjz2001** [Sora233/DDBOT#62]
我的服务器在外国，如果不扫码的话根本无法登录。

**Comment by Sora233** [comment]
有空我会看一下

**Comment by wjz2001** [comment]
> 有空我会看一下

有没有可能直接适配cqhttp框架？

**Comment by Sora233** [comment]
> > 有空我会看一下
> 
> 有没有可能直接适配cqhttp框架？

不会适配，一开始的目的就是想要无依赖部署
