### ISSUE TITLE
【bug反馈】/config at @特定成员功能失效

### ISSUE THREAD

**Issue by wjz2001** [Sora233/DDBOT#68]
这个功能使用以后过一段时间就会失效，必须重新键入命令才能再次起效

**Comment by Sora233** [comment]
失效的时候 /config at show也显示为空了吗

**Comment by wjz2001** [comment]
> 失效的时候 /config at show也显示为空了吗

是的

**Comment by Sora233** [comment]
> > 失效的时候 /config at show也显示为空了吗
> 
> 是的

按格式私聊一下bot，我具体看一下日志
```
#68 发生的QQ群号码
```

**Comment by wjz2001** [comment]
> > > 失效的时候 /config at show也显示为空了吗
> > 
> > 
> > 是的
> 
> 按格式私聊一下bot，我具体看一下日志
> 
> ```
> #68 发生的QQ群号码
> ```

现在可能不行，因为我在反馈前已经重新订阅了一下，所以现在还是有效的

**Comment by Sora233** [comment]
没关系，先尝试看一下当时的日志

**Comment by lanzhitao** [comment]
第一次配置机器人~使用了1561991863 config配置后提示成功,名字正确 
之后at show提示参数解析失败 - expected "<action>"

**Comment by lanzhitao** [comment]
第一次配置机器人 有推送,但是不会@所有人 设置已经提示成功

**Comment by Sora233** [comment]
> 第一次配置机器人 有推送,但是不会@所有人 设置已经提示成功

@全员因为有次数限制并不一定能正常使用，请在私人部署的bot上使用这个功能。

**Comment by wjz2001** [comment]
> > > 失效的时候 /config at show也显示为空了吗
> > 
> > 
> > 是的
> 
> 按格式私聊一下bot，我具体看一下日志
> 
> ```
> #68 发生的QQ群号码
> ```

又出现了这个问题，这回/config at show有内容，就是订阅的qq号
日志我私信bot没反应，我是把logs文件夹下的日志传上来还是把miraigo-logs文件夹下的日志传上来？

**Comment by Sora233** [comment]
> > > > 失效的时候 /config at show也显示为空了吗
> > > 
> > > 
> > > 是的
> > 
> > 
> > 按格式私聊一下bot，我具体看一下日志
> > ```
> > #68 发生的QQ群号码
> > ```
> 
> 又出现了这个问题，这回/config at show有内容，就是订阅的qq号
> 日志我私信bot没反应，我是把logs文件夹下的日志传上来还是把miraigo-logs文件夹下的日志传上来？

先确认一下at的触发时机，目前只有上播推送能够触发，下播和改标题不能触发，确认下是不是这个问题

**Comment by wjz2001** [comment]
> > > > > 失效的时候 /config at show也显示为空了吗
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 按格式私聊一下bot，我具体看一下日志
> > > ```
> > > #68 发生的QQ群号码
> > > ```
> > 
> > 
> > 又出现了这个问题，这回/config at show有内容，就是订阅的qq号
> > 日志我私信bot没反应，我是把logs文件夹下的日志传上来还是把miraigo-logs文件夹下的日志传上来？
> 
> 先确认一下at的触发时机，目前只有上播推送能够触发，下播和改标题不能触发，确认下是不是这个问题

上播不触发，必须重新添加才能重新触发

**Comment by Sora233** [comment]
已有一段时间没有发现具体问题，如果发现有继续发生的，可以重开这个issue
