### ISSUE TITLE
[FEATURE]希望添加一个针对所有群的开关命令

### ISSUE THREAD

**Issue by MEYUYU** [Sora233/DDBOT#70]
希望添加一个针对所有群的开关命令
例如:
/disable help或者/disable -g all_group help
可以关闭所有群的help命令
一个群一个群的输入实在太麻烦了

**Comment by Sora233** [comment]
合理，近期会加上

**Comment by Sora233** [comment]
再描述一下场景，是私有场景的Admin操作吗，还是任意用户只它操作有权限操作的

**Comment by MEYUYU** [comment]
个人搭建的bot环境下，admin通过私聊bot统一关闭某功能，用来限制其他用户和群管理使用，主要是关闭help和watch功能。

**Comment by Sora233** [comment]
0653129567c56fa600dd0d1628b2e86ee4d32ed9 已实现，将于v0.0.16发布
