### ISSUE TITLE
[BUG] 私有部署订阅成功，发送群消息失败

### ISSUE THREAD

**Issue by thrfox** [Sora233/DDBOT#78]
/watch指令已经订阅成功
查看后台日志报错
`{"GroupCode":4881551,"content":"啊啦哎哟喂正在直播\nhttps://live.bilibili.com/413280[Image]","level":"error","module":"me.sora233.Lsp","msg":"发送群消息失败","time":"2021-08-04T12:53:24+08:00"}`
第一次测试时已经可以正常推送，第二天再开播时显示该报错
/log 指令查询显示【无结果】

操作系统版本：ubuntu 16
BOT版本：0.0.18

**Comment by Sora233** [comment]
是否是扫码登陆？

**Comment by thrfox** [comment]
> 是否是扫码登陆？

是扫码登录
而且根据[](https://github.com/Mrs4s/go-cqhttp/issues/958)
进行了如下操作
1. 停止gocqhttp
2. 删除gocqhttp_data下的device.json
3. 在手机上登陆qq删除mirai设备登陆信息
4. 确保配置文件中qq密码为空
5. 启动gocqhttp,进行扫码登陆验证

另外根据[](https://github.com/Mrs4s/go-cqhttp/issues/211)
更改了device.json的protocol 为1 安卓协议后重启并没有生效

**Comment by Sora233** [comment]
尝试用帐号密码登陆
