### ISSUE TITLE
希望添加acfun平台的支持

### ISSUE THREAD

**Issue by VALIGARMANDA555** [Sora233/DDBOT#87]
虽然别人做的已经有这功能了（https://github.com/orzogc/acfunlive ） 但是我不想开多一个程序

**Comment by Sora233** [comment]
开发版内 257e0ec25d504562a7a0e71e65783c6968dae148 已经支持，正式版将随1.0版本一起发布

**Comment by Sora233** [comment]
v1.0.0版本已经发布
