### ISSUE TITLE
[BUG]进程突然结束

### ISSUE THREAD

**Issue by lingyuanzhicheng** [Sora233/DDBOT#97]
**详细描述**
日常挂在云电脑上，当聊天信息过多窗口回显聊天记录很多，侧边滑条快到底部时，会自动关闭。

**正常情况应该是怎样的**
平时都很正常，就聊天过多时就会突然没了。

**截图**
截图木有

**如果是私有部署**
操作系统版本：WindowsServer2016
BOT版本：v0.1.4

**Comment by Sora233** [comment]
- 是否频繁
- 检查logs文件夹内的日志，找到挂掉的时间点，看是否有错误发生
