### ISSUE TITLE
[BUG]微博推送图片很模糊

### ISSUE THREAD

**Issue by MEYUYU** [Sora233/DDBOT#98]
微博推送附带的图片都很模糊
如图,大图为网页上的效果,小图为QQ推送的尺寸
![Snipaste_2021-11-20_16-02-54](https://user-images.githubusercontent.com/3656262/142719241-856b6c76-8243-4099-add1-0b3ee4383238.png)

操作系统版本：
BOT版本：v1.0.0

**Comment by Sora233** [comment]
by design
可以新增一下配置支持使用高清图

**Comment by Sora233** [comment]
v1.0.4版本已使用原图
